# -*- coding: utf-8 -*-
"""Binary_num.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x40k8eOBsP7_xcs-AlQS8mzy6_OYEiNh
"""

!pip install qiskit-Aer

# Commented out IPython magic to ensure Python compatibility.
from qiskit import *
from qiskit.tools.visualization import array_to_latex, plot_bloch_multivector, plot_state_qsphere, plot_histogram
from numpy import pi
# %matplotlib inline

cr = QuantumCircuit(3)

cr.ry(2*pi/3,0)
cr.ch(0,1)
cr.cnot(1,2)
cr.cnot(0,1)
cr.x(0)

cr.draw()

simulator = Aer.get_backend('statevector_simulator')
result = execute(cr, backend=simulator).result()
statevector = result.get_statevector()
array_to_latex(statevector, prefix="\\text{statevector = }\n")

cr.measure_all()
simulator = Aer.get_backend('qasm_simulator')
result = execute(cr, backend=simulator, shot =3).result()
array_to_latex(statevector)

plot_histogram(result.get_counts())



from qiskit_ibm_runtime import QiskitRuntimeService
from qiskit.tools.monitor import job_monitor
IBMQ.save_account('Token number here ')
provider = IBMQ.load_account()

qcomp = provider.get_backend('ibm_brisbane')
job = execute(cr, backend = qcomp)
job_monitor(job)

qcomp_result = job.result()
plot_histogram(qcomp_result.get_counts())

