# -*- coding: utf-8 -*-
"""Quantum_Teleportation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11DKWAVc0BRi3-ZgQEclqnEetgba38hel
"""

from qiskit import *
from qiskit.quantum_info import Statevector, DensityMatrix, SparsePauliOp
from qiskit.tools.visualization import plot_bloch_multivector, plot_state_qsphere, plot_histogram, array_to_latex
from qiskit import QuantumCircuit, Aer, execute, transpile, QuantumRegister, ClassicalRegister
from numpy import pi

circuit = QuantumCircuit(3,2)
circuit.h(2)
circuit.barrier()

# create Bell state pair
circuit.h(1)
circuit.cx(1, 0)
circuit.barrier()

# Olivia performs Bell state measurement
circuit.cx(2, 1)
circuit.h(2)
circuit.barrier()

circuit.cx(1,0)
circuit.cz(2,0)

circuit.barrier()

# Barron transforms his qubit based on measurement results
#circuit.x(q0).c_if(crx, 1)  # apply X gate if cr_x is 1
#circuit.z(q0).c_if(crz, 1)  # apply Z gate if cr_z is 1
circuit.measure(0,0)
circuit.draw(output='mpl')



simulator = Aer.get_backend('statevector_simulator')
result = execute(circuit, backend=simulator).result()
statevector = result.get_statevector()
array_to_latex(statevector, prefix="\\text{statevector = }\n")

simulator = Aer.get_backend('qasm_simulator')
result = execute(circuit, backend=simulator, shot =3).result()
array_to_latex(statevector)

plot_histogram(result.get_counts())

from qiskit_ibm_runtime import QiskitRuntimeService
from qiskit.tools.monitor import job_monitor
IBMQ.save_account('Token number here')
provider = IBMQ.load_account()

qcomp = provider.get_backend('ibm_brisbane')
job = execute(circuit, backend = qcomp)
job_monitor(job)

qcomp_result = job.result()
plot_histogram(qcomp_result.get_counts())



